on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Build App
        run: |
          yarn --frozen-lockfile
          yarn build:win64
          yarn build-update
      - name: Rename release asset
        if: success()
        shell: pwsh
        run: Rename-Item -Path ./build/app.zip -NewName StarRailWarpExport.zip
      - name: Create Release & Upload Asset
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/StarRailWarpExport.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy update
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          commit_message: Update app
          build_dir: ./build/update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
